### ISSUE TITLE
Monthly View Calendar Functionality

### ISSUE THREAD

**Issue by lauT0** [cse110-sp24-group16/cse110-sp24-group16#73]
## Description
Get monthly view calendar functionality with js. It should be able to accurately go through the months of the year using buttons

## Acceptance Criteria
- [x] accurate monthly view
- [x] month chances upon using navigation buttons

## Tasks

- [x] remove html hardcoding
- [x] create function for loading the calendar for the month
- [x] create event listeners for the buttons and load the correct month

## Context
Using this video to help with coding, no external calendar dependencies for scripting
https://youtu.be/v-y3B91Fhiw?si=ZvUl8KydSGA1zr9L

## Screenshots/Mockups
Not applicable

## Testing Notes
- ensure the functions months match to the real calendar, and all functionality works manually

## Assignees
_Who is responsible for addressing this issue?_

/assign @lauT0 

## Labels

/label enhancement
